<form method="post" class="jNice" action="?system=SEO&page=edit" name="edit">
    <h4>%WEBSITE_KEYWORDS_LOCALE%</h4>
    <div id="textarea">
      	 <p>%KEYWORDS_HELP_LOCALE%: ','</p>
         <textarea cols="60" rows="18" name="seokeywords">%SEOKEYWORDS%</textarea>
    </div>
        
	<h4>%SEO_DESCRIPTION_LOCALE%</h4>
    <div id="textarea">
             <p>%SEO_DESCRIPTION_HELP_LOCALE%</p>
             <textarea cols="60" rows="18" name="seodescription">%SEODESCRIPTION%</textarea>
    </div>
    <br />
                
	<input type="submit" value="%SAVE_LOCALE%">
</form>