<form method="post" class="jNice" action="?system=SEO&page=edit" name="edit">
    <h3>Website Keywords</h3>
    <div id="textarea">
      	 <p>Approximately 30 keywords separated by commas: ','.</p>
         <textarea cols="60" rows="18" name="seokeywords">%SEOKEYWORDS%</textarea>
    </div>
        
	<h3>SEO Description</h3>
    <div id="textarea">
             <p>Short description of your website of around 25 words.</p>
             <textarea cols="60" rows="18" name="seodescription">%SEODESCRIPTION%</textarea>
    </div>
    <br />
                
	<input type="submit" value="Save">
</form>
<br /><br />