	<div class="inactiveTab">
		<a href="?system=GeneralSettings&page=edit">General Settings</a>
	</div>
	<div class="activeTab">
		<a href="?system=SEO&page=edit">SEO Settings</a>
	</div>
	<div class="inactiveTab">
		<a href="?system=Template&page=change">Template Settings</a></li>
	</div>
	<div class="inactiveTab">
		<a href="?system=Editor&page=clearCache">Clear Cache</a></li>
	</div>
<div class="tabSpacer">
&nbsp;
</div>