	<div class="%ONE%Tab">
		<a href="?system=GeneralSettings&page=edit">%GENERAL_SETTINGS_LOCALE%</a>
	</div>
	<div class="%TWO%Tab">
		<a href="?system=SEO&page=edit">%SEO_SETTINGS_LOCALE%</a>
	</div>
	<div class="%THREE%Tab">
		<a href="?system=Template&page=change">%TEMPLATE_SETTINGS_LOCALE%</a></li>
	</div>
	<div class="%FOUR%Tab">
		<a href="?system=Editor&page=clearCache">%CLEAR_CACHE_LOCALE%</a></li>
	</div>
<div class="tabSpacer">
&nbsp;
</div>
