<form method="post" action="index.php?system=Contact&page=submit"><br />
	<label for="name"><span style="font-size: 12px;font-weight:bold;">Name:</span></label><br />
	<input type="text" name="name" id="name"><br /><br />
	<label for="email"><span style="font-size: 12px;font-weight:bold;">Email:</span></label><br />
	<input type="text" name="email" id="email"><br /><br />
	<label for="message"><span style="font-size: 12px;font-weight:bold;">Message:</span></label><br />
	<textarea name="message" cols="36" rows="6"></textarea><br /><br />
	<input id="send" style="margin-top: 10px;" type="submit" value="Send">
</form>		