<form method="post" class="jNice" action="index.php?system=Modules&page=admin&active=Contact" name="edit">You are editing the contact plugin. In order to use this plugin link users to ROOT/index.php?system=Contact&page=index<br />
	<h4>Messaging E-mail</h4><br /> 
	<fieldset><input name="email" class="text-long" value="%EMAIL%"></fieldset>
	<h4>Messaging Subject</h4><br /> 
	<fieldset><input name="subject" class="text-long" value="%SUBJECT%"></fieldset>
	<h4>Title of contact page</h4><br /> 
	<fieldset><input name="title" class="text-long" value="%TITLE%"></fieldset>
     <input type="submit" value="Save" />
</form>