<form method="post" class="jNice" action="?system=Editor&page=editor&active=%UNIX%" name="edit">%YOU_ARE_EDITING_LOCALE%: %TITLE% (%UNIX%)<br />
                <h4>%TITLE_LOCALE%</h4><br /> <fieldset><input name="title" class="text-long" value="%TITLE%"></fieldset>
        
                <h4>%TEMPLATE_LOCALE%</h4><br />
		<fieldset>	<select name="template">
                                                %CURRENT_TEMPLATE%
						%TEMPLATE_OPTIONS%
				</select>
		</fieldset>
                
        <h4>%CONTENT_LOCALE%</h4><br />
                    </div><div id="textarea">
                        <textarea cols="60" rows="18" id="pagedata" name="pagedata">%CONTENT%</textarea>
                    </div><div id="main">
                <br />
                
        <input type="submit" value="%SAVE_LOCALE%"><br /><br /></form>
<script> 
    $(function() {
        $( "input:submit" ).button();
        $( ".buttonBit" ).button();
    });
</script> 