<form method="post" class="jNice" action="?system=Editor&page=editor&active=%UNIX%" name="edit">%YOU_ARE_EDITING_LOCALE%: %TITLE% (%UNIX%)<br />
                <h3>%TITLE_LOCALE%</h3><br /> <fieldset><input name="title" class="text-long" value="%TITLE%"></fieldset>
        
                <h3>%TEMPLATE_LOCALE%</h3><br />
		<fieldset>	<select name="template">
                                                %CURRENT_TEMPLATE%
						%TEMPLATE_OPTIONS%
				</select>
		</fieldset>
                
        <h3>%CONTENT_LOCALE%</h3><br />
                    </div><div id="textarea">
                        <textarea cols="60" rows="18" id="pagedata" name="pagedata">%CONTENT%</textarea>
                    </div><div id="main">
                <br />
                
        <input type="submit" value="%SAVE_LOCALE%"><br /><br /></form>