<p>%UNIX_NAME_TEXT_GENERATED_LOCALE%</p><br /><form method="post" class="jNice" action="?system=Editor&page=createPage" name="edit">%YOU_EDITING_UNTITLED_LOCALE%<br />
                <h4>%TITLE_LOCALE%</h4><br /> <fieldset><input name="title" class="text-long" value=""><br /><a href="#" onclick="javascript:$('#unix').show();">%DEFINE_UNIX_NAME_MANUALLY_LOCALE%</a></fieldset>
                
                
                <div id="unix" style="display: none;"><h3>%UNIX_NAME_LOCALE%</h3><br /> <fieldset><input name="unix" class="text-long" value=""></fieldset></div>
				<br />
		<h4>%TEMPLATE_LOCALE%</h4><br />
		<fieldset>	<select name="template">
						%TEMPLATE_OPTIONS%
				</select>
		</fieldset>
        
		<h4>%CONTENT_LOCALE%</h4><br />
                    </div><div id="textarea">
                        <textarea cols="60" rows="18" id="pagedata" name="pagedata"></textarea>
                    </div><div id="main">
                <br />
                
<input type="submit" value="%SAVE_LOCALE%"><br /><br /></form>
<script> 
    $(function() {
        $( "input:submit" ).button();
    });
</script> 
<input type="hidden" name="lang" id="lang" value="%LOCALE%" />