	<div class="%ONE%Tab">
		<a href="?system=GeneralSettings&page=edit">%PAGELIST_LOCALE%</a>
	</div>
	<div class="%TWO%Tab">
		<a href="?system=Editor&page=createPage">%CREATE_NEW_PAGE_LOCALE%</a>
	</div>
<div class="tabSpacer">
&nbsp;
</div>
<div style="font-family: arial, helvetica, sans serif;text-align:left;">
<h4 id="pagetitle">%PAGE_TITLE_LOCALE%</h4><input type="text" name="filter" value="%TYPE_FILTER_LOCALE%" id="filter">
<div id="clearbits"></div>
<div id="noresults" style="display:none;">%NO_RESULTS_LOCALE%</div>
<input id="viewText" value="%VIEW_LOCALE%" type="hidden" />
<input id="editText" value="%EDIT_LOCALE%" type="hidden" />
<input id="deleteText" value="%DELETE_LOCALE%" type="hidden" />