	<div class="yes" style="font-size: 13px;"></div>
	<div class="%ONE%Tab">
		<a href="?system=UsersList&page=list">%USERLIST_LOCALE%</a>
	</div>
	<div class="%TWO%Tab">
		<a href="?system=Users&page=create">%CREATE_NEW_USER_LOCALE%</a>
	</div>
<div class="tabSpacer">
&nbsp;
</div>

<h4 id="pagetitle">%USER_TITLE_LOCALE%</h4><input type="text" name="filter" value="%USER_TYPE_FILTER_LOCALE%" id="filter">
<div id="clearbits"></div>
<div id="noresults" style="display:none;">%NO_RESULTS_LOCALE%</div>
<input id="viewText" value="" type="hidden" />
<input id="editText" value="%EDIT_LOCALE%" type="hidden" />
<input id="deleteText" value="%DELETE_LOCALE%" type="hidden" />
