			<form method="POST" action="index.php?system=Admin&page=loginSubmit" id="contactform">
		    	<input type="hidden" name="returnto" value="index.php">
		                <label for="name"><h4>Your Username<font color="red">*</font></h4></label>

		                <input id="username" name="username" class="text" /><br /><br />
		                <label for="email"><h4>Your Password<font color="red">*</font></h4></label>
		                <input id="password" name="password" type="password" class="text" /><br /><br />
		                <input type="submit" value="Login"/><br />
		  </form>  	    
		  <p>
		  	<a href="index.php?system=admin&page=forgot_password">Forgot your password?</a>
		  </p>
		  <p>
		  	&nbsp;
		  </p>