
<div class="activeTab">
	<a href="index.php?system=Modules&page=load&active=%UNIX%">%MODULE_INFORMATION_LOCALE%</a>
</div>
<div class="inactiveTab">
	%ADMINISTRATION%
</div>
<div class="tabSpacer">
	&nbsp;
</div>
<div style="display: block;">
	<p style="font-weight: bold;display:block;">%MODULE_INFORMATION_LOCALE%:</p>
	<div style="float: left;">
		<img alt="module logo" src="%IMAGE%" />
	</div>
	<div style="float: left;">
	<p>
		<ul>
			<li><b>%TITLE_LOCALE%:</b> %TITLE%</li>
			<li><b>%AUTHOR_LOCALE%:</b> %AUTHOR%</li>
			<li><b>%VERSION_NUMBER_LOCALE%:</b> %VERSION%</li>
			<li><b>%SUPPORT_AVAILABLE_AT_LOCALE%:</b> <a href="%SUPPORT%">%SUPPORT%</a></li>
			<li><b>%ORGANISATION_LOCALE%:</b> %ORGANISATION%</li>
		</ul>
	</p>
	</div>
</div>