
<div class="activeTab">
	<a href="index.php?system=Modules&page=load&active=%UNIX%">Module Information</a>
</div>
<div class="inactiveTab">
	%ADMINISTRATION%
</div>
<div class="tabSpacer">
	&nbsp;
</div>
<div style="display: block;">
	<p style="font-weight: bold;display:block;">Module Information:</p>
	<div style="float: left;">
		<img alt="module logo" src="%IMAGE%" />
	</div>
	<div style="float: left;">
	<p>
		<ul>
			<li><b>Title:</b> %TITLE%</li>
			<li><b>Author:</b> %AUTHOR%</li>
			<li><b>Version Number:</b> %VERSION%</li>
			<li><b>Support Available At:</b> <a href="%SUPPORT%">%SUPPORT%</a></li>
			<li><b>Organisation:</b> %ORGANISATION%</li>
		</ul>
	</p>
	</div>
</div>