<form method="post" action="?system=Users&page=edit&active=%USERNAME%" name="edit">
                <h4>%USERNAME_LOCALE%</h4><br /> <fieldset>'%USERNAME%'</fieldset>
                
                <h4>%FULLNAME_LOCALE%</h4><br /> <fieldset><input name="name" class="text-long" value="%FULLNAME%" /></fieldset>
                
                <h4>%EMAIL_LOCALE%</h4><br /> <fieldset><input name="email" class="text-long" value="%EMAIL%" /></fieldset>
        
        		<h4>%PASSWORD_LOCALE%</h4><br /> <fieldset><div class="txtblock">%NEW_PASSWORD_LOCALE%:</div><input name="password1" class="text-aligned" type="password" value="" /><br /><div class="txtblock">%VERIFY_PASSWORD_LOCALE%:</div><input name="password2" type="password" class="text-aligned" value="" /></fieldset>
        		
        		<h4>%ACCESSLEVEL_LOCALE%</h4>
        		<fieldset>
	        		<select name="access">
						<option>%OPTION1%</option>
						<option>%OPTION2%</option>
					</select>
				</fieldset>
                
<input type="submit" value="%SAVE_LOCALE%"></form><br /><br />