<form method="post" action="?system=Users&page=create" name="edit">
                <h4>%USERNAME_LOCALE%</h4><br />(%USERNAME_WARNING_LOCALE%) <fieldset><input name="username" class="text-long" value="" /></fieldset>
                
                <h4>%FULLNAME_LOCALE%</h4><br /> <fieldset><input name="name" class="text-long" value="" /></fieldset>
                
                <h4>%EMAIL_LOCALE%</h4><br /> <fieldset><input name="email" class="text-long" value="" /></fieldset>
        
        		<h4>%PASSWORD_LOCALE%</h4><br /> <fieldset><span class="txtblock">%NEW_PASSWORD_LOCALE%:</span><input name="password1" type="password" class="text-aligned" value="" /><br /><span class="txtblock">%VERIFY_PASSWORD_LOCALE%:</span><input name="password2" type="password" class="text-aligned" value="" /></fieldset>
        		
        		<h4>%ACCESSLEVEL_LOCALE%</h4>
        		<fieldset>
	        		<select name="access">
						<option>Editor</option>
						<option>Administrator</option>
					</select>
				</fieldset>
                
<input type="submit" value="%SAVE_LOCALE%"></form><br /><br />