<form method="post" class="jNice" action="index.php?system=Modules&page=admin&active=Menu&req=save&id=%MENU_ID%" name="edit">You are creating a new menu item.<br />
                <h3>Title</h3><br /> <fieldset><input name="title" class="text-long" value="%TITLE%"></fieldset>
               
       			<h3>External Link</h3>Not Required if Internal page is selected.
       			<br /> 
       			<fieldset><input name="external" class="text-long" value="%EXTERNAL_LINK%"></fieldset>
       			
       			<h3>Internal Page</h3>Not required if External link is entered.
       			<br /> <fieldset><p>%INTERNAL_PAGES%</p></fieldset>
                
<input type="submit" value="Save"><br /><br /></form>