<form method="post" class="jNice" action="index.php?system=Modules&page=admin&active=Menu&req=save&id=%MENU_ID%" name="edit">
                <h4>%TITLE_LOCALE%</h4><br /> <fieldset><input name="title" class="text-long" value="%TITLE%"></fieldset>
               
       			<h4>%EXTERNAL_LINK_LOCALE%</h4>%EX_LINK_MESS_LOCALE%
       			<br /> 
       			<fieldset><input name="external" class="text-long" value="%EXTERNAL_LINK%"></fieldset>
       			
       			<h4>%INTERNAL_PAGE_LOCALE%</h4>%INTERNAL_PAGE_MSG_LOCALE%
       			<br /> <fieldset><p>%INTERNAL_PAGES%</p></fieldset>
                
                <h4>%OPEN_WINDOW_LOCALE%</h4>
                <fieldset>
                <input type="radio" name="state" value="sw" %SWCHECKED%> %OPEN_IN_SAME_WINDOW_LOCALE%<br />
                <input type="radio" name="state" value="nw" %NWCHECKED%> %OPEN_IN_NEW_WINDOW_LOCALE%
                </fieldset>
                <input type="submit" value="%SAVE_LOCALE%"><br /><br /></form>